name: TodoWorkflow
on:
  push:
    branches:
      ["main"]  
  pull_request:
    branches:
      ["main"]

jobs:
  integration-delivery:
    runs-on: ubuntu-latest
    environment: Test
    container:
      image: node
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name:  Install dependencies
          run: npm install
        - name: Run tests
          run: npm test

        - name: Build website 
          run: npm run build